export type Lang = "sl" | "hr" | "en";
export const LANGS: { code: Lang; label: string }[] = [
  { code: "sl", label: "SLO" },
  { code: "hr", label: "HR" },
  { code: "en", label: "EN" },
];

type Dict = {
  promo: string;
  nav: { kako: string; funkcije: string; cene: string; kontakt: string; demo: string; cta: string };
  hero: { badge: string; h1a: string; h1b: string; sub: string; cta1: string; cta2: string; c1: string; c2: string };
  trust: { label: string; words: string[] };
  kako: { eyebrow: string; h2: string; p: string; steps: { title: string; text: string }[] };
  asset: { eyebrow: string; h2a: string; h2accent: string; h2b: string; p: string; bullets: string[]; note: string; count: string; grows: string; sendAll: string };
  dash: { eyebrow: string; h2: string; p: string; feats: [string, string][]; cta: string; range: string; hours: string };
  feat: { eyebrow: string; h2: string; p: string; gBadge: string; gH3: string; gP: string; gWas: string; gNew: string; gChart: string; items: { label: string; title: string; text: string }[] };
  story: { eyebrow: string; h2a: string; h2b: string; p: string; left: string };
  cene: { eyebrow: string; h2: string; p: string; trial: string; note: string; popular: string; plans: { name: string; tagline: string; price: string; period: string; cta: string; features: string[] }[] };
  faq: { eyebrow: string; h2: string; items: { q: string; a: string }[] };
  finalCta: { h2: string; p: string; cta1: string; cta2: string };
  footer: { tagline: string; product: string; company: string; legal: string; lProdukt: string[]; lPodjetje: string[]; lPravno: string[]; rights: string };
  kontakt: { eyebrow: string; h1: string; p: string; bullets: string[]; or: string; formTitle: string; fName: string; fVenue: string; fEmail: string; fPhone: string; fType: string; fCity: string; fGuests: string; fHeard: string; fMsg: string; fMsgPh: string; choose: string; send: string; sending: string; consent: string; doneH: string; doneP: string; doneCta: string; errBoth: string; types: string[]; guests: string[]; heard: string[] };
};

const sl: Dict = {
  promo: "🎉 Uvodna promocija — 14 dni brezplačno, brez kartice · postavi stran v 5 minutah →",
  nav: { kako: "Kako deluje", funkcije: "Funkcije", cene: "Cene", kontakt: "Kontakt", demo: "Poglej demo", cta: "Ustvari stran" },
  hero: { badge: "Zvestoba · Google ocene · marketing — za lokale", h1a: "Stalni gosti se ne zgodijo. ", h1b: "Zgradiš jih.", sub: "Gost skenira QR z računa in nabira žige — brez aplikacije. Ti pa zgradiš bazo rednih gostov in njihovih kontaktov, ki jo lahko kadarkoli nagovoriš — nove ponudbe, win-back, rojstni dnevi — in ti prinese Google ocene.", cta1: "Ustvari svojo stran", cta2: "Poglej demo v živo", c1: "Postavljeno v 5 minutah", c2: "Brez provizije na obisk" },
  trust: { label: "Narejeno za:", words: ["Kavarne", "Bistroji", "Slaščičarne", "Picerije", "Pekarne"] },
  kako: { eyebrow: "Tako preprosto je", h2: "Od računa do žiga v treh sekundah", p: "Vsak slovenski fiskalni račun nosi QR kodo. Gost jo skenira, sistem preveri izdajatelja in datum — žig je tu.", steps: [
    { title: "Skenira račun", text: "Gost odpre tvojo stran prek QR na mizi in poskenira QR na dnu računa. Brez prenosa aplikacije." },
    { title: "Dobi žig", text: "Štampiljka tlesne na kartonček — kot nekoč na papirju, le da je tu trajno." },
    { title: "Unovči nagrado", text: "Poln kartonček = brezplačna kava. Gost pokaže kodo, osebje potrdi z dotikom. Vrne se hitreje, kot misliš." },
  ] },
  asset: { eyebrow: "Tvoja prava prednost", h2a: "Vsak gost postane kontakt v ", h2accent: "tvoji", h2b: " bazi", p: "Vsakič ko nekdo skenira, dobiš novega rednega gosta — telefon ali email + vzorec obiskov. Baza raste sama in je samo tvoja. Kadarkoli jo lahko nagovoriš:", bullets: ["Promoviraj novo ponudbo ali jed", "Najavi sezonske akcije in dogodke", "Sporoči novosti lokala", "Vrni neaktivne, razveseli za rojstni dan"], note: "Brez Facebooka, brez plačanih oglasov — pišeš direktno tistim, ki že hodijo k tebi.", count: "rednih gostov · +12 ta mesec", grows: "↑ raste", sendAll: "Pošlji vsem ponudbo" },
  dash: { eyebrow: "Tvoja nadzorna plošča", h2: "Vidiš, kdo se vrača — in kdaj", p: "Koliko skeniranj, koliko novih strank, ob katerih urah je gneča in kdo so tvoji najboljši gostje. Brez tabel v Excelu.", feats: [["Analitika v živo", " — skeniranja, obiski po urah, pogostost vračanja."], ["QR plakat za mizo", " — prenesi PNG ali PDF in natisni v minuti."], ["Seznam strank", " — kdo je nov, kdo reden, koga si že dolgo ni videl."]], cta: "Razišči nadzorno ploščo", range: "Zadnjih 30 dni", hours: "Obiski po urah" },
  feat: { eyebrow: "Več kot žigi", h2: "Cel stroj za stalne goste", p: "Loyalty ujame tvoje redne goste in njihove kontakte. Vse ostalo jih pripelje nazaj — in ti prinese Google ocene.", gBadge: "⭐ Google ocene na avtopilotu", gH3: "Več zadovoljnih gostov = več ocen na Googlu", gP: "Ko gost dobi žig (zadovoljen!), ga samodejno povabimo k oceni. Slabe izkušnje prestrežemo zasebno — tvoj profil dobi le dobre ocene, ti pa višje v Google iskanju.", gWas: "prej 3,9★", gNew: "novih ocen / 6 mes", gChart: "Nove Google ocene / mesec", items: [
    { label: "Kolo sreče", title: "Mimoidoče spremeni v stalne goste", text: "Na tvoji spletni strani ali QR plakatu obiskovalci zavrtijo kolo, osvojijo nagrado in se registrirajo. Vsak vrtljaj = nov kontakt, ki ga lahko pripelješ nazaj." },
    { label: "Win-back", title: "Pripelji nazaj tiste, ki so izginili", text: "Sistem sam opazi, kdo že 3 tedne ni bil, in mu pošlje »pogrešamo te« + bonus. Gost, ki bi sicer šel h konkurenci, se vrne — ti pa ne narediš nič." },
    { label: "Rojstni dan", title: "Razveseli točno ob rojstnem dnevu", text: "Datum zberemo ob registraciji. Na rojstni dan gostu samodejno pošljemo darilo — eden najmočnejših razlogov za vrnitev." },
    { label: "SMS + email", title: "Doseži vse goste z enim klikom", text: "Ciljaj segmente — aktivni, neaktivni, najboljši, rojstni dnevi. Pred pošiljanjem ti pokažemo točen strošek, da nikoli ne plačaš preveč." },
    { label: "Kuponi", title: "Pošlji nagrade, ki res pripeljejo nazaj", text: "Sporočilu priloži pravi kupon (npr. brezplačna kava) z veljavnostjo in opomnikom pred potekom — konkretna spodbuda, ne le besede." },
    { label: "Profili gostov", title: "Spoznaj, kdo so tvoji najboljši", text: "Klikni gosta in vidiš vse: obiske, porabo, kako pogosto se vrača, kdaj nazadnje. Veš, koga nagraditi in koga pripeljati nazaj." },
  ] },
  story: { eyebrow: "Naša ena zapomljiva stvar", h2a: "Občutek pravega žiga,", h2b: "brez papirja v žepu", p: "Kartončki zvestobe so delovali, ker so bili otipljivi. Ohranili smo točno ta moment — žig, ki tlesne ob skenu — le da ga ni mogoče izgubiti ali pozabiti doma.", left: "9 / 10 — še en obisk ☕" },
  cene: { eyebrow: "Cene", h2: "Izberi svojo skodelico", p: "Brez provizije na obisk, brez vezave. 14 dni brezplačno — brez kartice.", trial: "✓ 14 dni brezplačen preizkus na vseh paketih", note: "Vse cene brez DDV · prekličeš kadarkoli · 14 dni brezplačno, brez kartice", popular: "Najbolj priljubljeno", plans: [
    { name: "Start", tagline: "Za en lokal, ki začenja", price: "49,99 €", period: "/ mesec", cta: "Začni 14 dni brezplačno", features: ["1 lokal", "QR stran za goste + kolo sreče", "Žigi ali točke + nagrade", "Do 50 strank", "Osnovna analitika"] },
    { name: "Grow", tagline: "Cel stroj za stalne goste", price: "79,99 €", period: "/ mesec", cta: "Začni 14 dni brezplačno", features: ["Vse iz Start", "Neomejeno strank", "⭐ Google ocene na avtopilotu", "Win-back & rojstnodnevne avtomatizacije", "SMS + email kampanje (segmenti)", "Profili gostov + polna analitika", "PDF/PNG plakati za mizo"] },
    { name: "Scale", tagline: "Za več lokalov pod eno znamko", price: "Po dogovoru", period: "", cta: "Pogovorimo se", features: ["Vse iz Grow", "Več lokalov, en dashboard", "Skupna analitika verige", "Preverjanje računov prek blagajne", "Prioritetna podpora + API"] },
  ] },
  faq: { eyebrow: "Pogosta vprašanja", h2: "Še kaj ti ni jasno?", items: [
    { q: "Mora gost naložiti aplikacijo?", a: "Ne. Stran se odpre v brskalniku prek QR kode na mizi. Registracija je en korak — Google ali telefonska številka, brez gesla." },
    { q: "Kako dobim več Google ocen?", a: "Samodejno. Ko gost dobi žig (torej zadovoljen), ga povabimo k oceni na Googlu. Slabe izkušnje prestrežemo zasebno, da popraviš, preden gre javno — tvoj profil tako dobi le dobre ocene." },
    { q: "Lahko pošljem sporočilo gostom, ki dolgo niso bili?", a: "Da. Vidiš segmente (aktivni, neaktivni 21+ dni, rojstni dnevi, najboljši) in jim z enim klikom pošlješ SMS ali email — ali pustiš, da gre samodejno." },
    { q: "Koliko stane pošiljanje sporočil?", a: "Email je praktično zastonj; SMS približno nekaj centov na kos — pred pošiljanjem ti pokažemo točen strošek, da ni presenečenj." },
    { q: "Deluje z mojo blagajno?", a: "Da. Vsak slovenski fiskalni račun nosi QR kodo — sistem prebere izdajatelja in čas izdaje neposredno iz nje. Vsak račun šteje le enkrat." },
    { q: "Koliko časa traja postavitev?", a: "Okoli pet minut: vpišeš ime, logo in barvo, fotografiraš vzorčni račun za aktivacijo, natisneš QR. Gostje lahko zbirajo žige še isti dan." },
  ] },
  finalCta: { h2: "Tvoja stalna kava se začne danes", p: "Ustvari stran, natisni QR, postavi ga na mize. Prve žige lahko podariš že popoldne.", cta1: "Ustvari svojo stran", cta2: "Najprej poglej demo" },
  footer: { tagline: "Zvestoba, Google ocene in marketing za slovenske lokale — gost skenira QR z računa, ti pa zgradiš bazo rednih gostov.", product: "Produkt", company: "Podjetje", legal: "Pravno", lProdukt: ["Funkcije", "Cene", "Kako deluje", "Demo za goste", "Demo dashboard"], lPodjetje: ["Kontakt", "Pogosta vprašanja", "Prijava za lokale"], lPravno: ["Splošni pogoji", "Politika zasebnosti", "Piškotki"], rights: "Vse pravice pridržane." },
  kontakt: { eyebrow: "Postavimo ti vse", h1: "Pridobimo ti več rednih gostov", p: "Pusti podatke in ti v enem dnevu vse postavimo — stran, kolo sreče, QR plakat. 14 dni brezplačno, brez kartice. Brez tveganja zate.", bullets: ["Vse postavimo namesto tebe", "Pokažemo demo na tvojem lokalu", "Brez vezave — odpoveš kadarkoli"], or: "Ali nam piši na", formTitle: "Pusti povpraševanje", fName: "Ime in priimek", fVenue: "Ime lokala", fEmail: "Email", fPhone: "Telefon", fType: "Tip lokala", fCity: "Mesto", fGuests: "Št. gostov", fHeard: "Kje si izvedel za nas?", fMsg: "Sporočilo (neobvezno)", fMsgPh: "Kaj te najbolj zanima?", choose: "Izberi …", send: "Pošlji povpraševanje", sending: "Pošiljam …", consent: "S pošiljanjem se strinjaš s politiko zasebnosti.", doneH: "Hvala! Javimo se ti.", doneP: "Tvoje povpraševanje smo prejeli. Kmalu te kontaktiramo in dogovorimo demo.", doneCta: "Nazaj na domov", errBoth: "Vpiši vsaj email ali telefon, da te lahko kontaktiramo.", types: ["Kavarna", "Bistro / restavracija", "Picerija", "Pekarna", "Slaščičarna", "Bar", "Frizer / salon", "Drugo"], guests: ["Do 50 / dan", "50–150 / dan", "150–300 / dan", "Več kot 300 / dan"], heard: ["Google", "Priporočilo znanca", "Instagram / Facebook", "Drugje"] },
};

const hr: Dict = {
  promo: "🎉 Uvodna promocija — 14 dana besplatno, bez kartice · postavi stranicu u 5 minuta →",
  nav: { kako: "Kako radi", funkcije: "Značajke", cene: "Cijene", kontakt: "Kontakt", demo: "Pogledaj demo", cta: "Izradi stranicu" },
  hero: { badge: "Vjernost · Google recenzije · marketing — za lokale", h1a: "Stalni gosti se ne dogode. ", h1b: "Izgradiš ih.", sub: "Gost skenira QR s računa i skuplja pečate — bez aplikacije. Ti gradiš bazu stalnih gostiju i njihovih kontakata koju možeš kontaktirati bilo kada — nove ponude, win-back, rođendani — i koja ti donosi Google recenzije.", cta1: "Izradi svoju stranicu", cta2: "Pogledaj demo uživo", c1: "Postavljeno u 5 minuta", c2: "Bez provizije po posjetu" },
  trust: { label: "Napravljeno za:", words: ["Kafiće", "Bistroe", "Slastičarnice", "Pizzerije", "Pekarnice"] },
  kako: { eyebrow: "Jednostavno je", h2: "Od računa do pečata u tri sekunde", p: "Svaki fiskalni račun nosi QR kod. Gost ga skenira, sustav provjeri izdavatelja i datum — pečat je tu.", steps: [
    { title: "Skenira račun", text: "Gost otvori tvoju stranicu putem QR-a na stolu i skenira QR na dnu računa. Bez preuzimanja aplikacije." },
    { title: "Dobije pečat", text: "Pečat sjedne na karticu — kao nekad na papiru, samo što je ovdje trajno." },
    { title: "Iskoristi nagradu", text: "Puna kartica = besplatna kava. Gost pokaže kod, osoblje potvrdi dodirom. Vrati se brže nego misliš." },
  ] },
  asset: { eyebrow: "Tvoja prava prednost", h2a: "Svaki gost postaje kontakt u ", h2accent: "tvojoj", h2b: " bazi", p: "Svaki put kad netko skenira, dobiješ novog stalnog gosta — telefon ili email + obrazac dolazaka. Baza raste sama i samo je tvoja. Možeš joj se obratiti bilo kada:", bullets: ["Promoviraj novu ponudu ili jelo", "Najavi sezonske akcije i događaje", "Javi novosti lokala", "Vrati neaktivne, razveseli za rođendan"], note: "Bez Facebooka, bez plaćenih oglasa — pišeš izravno onima koji već dolaze k tebi.", count: "stalnih gostiju · +12 ovaj mjesec", grows: "↑ raste", sendAll: "Pošalji svima ponudu" },
  dash: { eyebrow: "Tvoja kontrolna ploča", h2: "Vidiš tko se vraća — i kada", p: "Koliko skeniranja, koliko novih gostiju, u koje sate je gužva i tko su tvoji najbolji gosti. Bez tablica u Excelu.", feats: [["Analitika uživo", " — skeniranja, dolasci po satima, učestalost vraćanja."], ["QR plakat za stol", " — preuzmi PNG ili PDF i isprintaj u minuti."], ["Popis gostiju", " — tko je nov, tko stalan, koga dugo nije bilo."]], cta: "Istraži kontrolnu ploču", range: "Zadnjih 30 dana", hours: "Dolasci po satima" },
  feat: { eyebrow: "Više od pečata", h2: "Cijeli stroj za stalne goste", p: "Vjernost hvata tvoje stalne goste i njihove kontakte. Sve ostalo ih vraća — i donosi ti Google recenzije.", gBadge: "⭐ Google recenzije na autopilotu", gH3: "Više zadovoljnih gostiju = više recenzija na Googleu", gP: "Kad gost dobije pečat (zadovoljan!), automatski ga pozovemo na recenziju. Loša iskustva presretnemo privatno — tvoj profil dobije samo dobre recenzije, a ti viši rang u Google pretrazi.", gWas: "prije 3,9★", gNew: "novih recenzija / 6 mj", gChart: "Nove Google recenzije / mjesec", items: [
    { label: "Kolo sreće", title: "Prolaznike pretvori u stalne goste", text: "Na tvojoj web stranici ili QR plakatu posjetitelji zavrte kolo, osvoje nagradu i registriraju se. Svaki okret = novi kontakt koji možeš vratiti." },
    { label: "Win-back", title: "Vrati one koji su nestali", text: "Sustav sam primijeti tko 3 tjedna nije bio i pošalje mu »nedostaješ nam« + bonus. Gost koji bi inače otišao konkurenciji se vrati — bez tvog truda." },
    { label: "Rođendan", title: "Razveseli točno na rođendan", text: "Datum skupimo pri registraciji. Na rođendan gostu automatski pošaljemo dar — jedan od najjačih razloga za povratak." },
    { label: "SMS + email", title: "Dosegni sve goste jednim klikom", text: "Ciljaj segmente — aktivni, neaktivni, najbolji, rođendani. Prije slanja pokažemo točan trošak, da nikad ne platiš previše." },
    { label: "Kuponi", title: "Pošalji nagrade koje stvarno vraćaju", text: "Poruci priloži pravi kupon (npr. besplatna kava) s rokom i podsjetnikom prije isteka — konkretan poticaj, ne samo riječi." },
    { label: "Profili gostiju", title: "Upoznaj tko su tvoji najbolji", text: "Klikni gosta i vidiš sve: dolaske, potrošnju, koliko se često vraća, kada zadnji put. Znaš koga nagraditi i koga vratiti." },
  ] },
  story: { eyebrow: "Naša jedna pamtljiva stvar", h2a: "Osjećaj pravog pečata,", h2b: "bez papira u džepu", p: "Kartice vjernosti su radile jer su bile opipljive. Zadržali smo točno taj trenutak — pečat koji sjedne pri skeniranju — samo što ga ne možeš izgubiti ili zaboraviti kod kuće.", left: "9 / 10 — još jedan dolazak ☕" },
  cene: { eyebrow: "Cijene", h2: "Odaberi svoju šalicu", p: "Bez provizije po posjetu, bez ugovorne obveze. 14 dana besplatno — bez kartice.", trial: "✓ 14 dana besplatne probe na svim paketima", note: "Sve cijene bez PDV-a · otkažeš bilo kada · 14 dana besplatno, bez kartice", popular: "Najpopularnije", plans: [
    { name: "Start", tagline: "Za jedan lokal koji počinje", price: "49,99 €", period: "/ mjesec", cta: "Počni 14 dana besplatno", features: ["1 lokal", "QR stranica za goste + kolo sreće", "Pečati ili bodovi + nagrade", "Do 50 gostiju", "Osnovna analitika"] },
    { name: "Grow", tagline: "Cijeli stroj za stalne goste", price: "79,99 €", period: "/ mjesec", cta: "Počni 14 dana besplatno", features: ["Sve iz Start", "Neograničeno gostiju", "⭐ Google recenzije na autopilotu", "Win-back i rođendanske automatizacije", "SMS + email kampanje (segmenti)", "Profili gostiju + puna analitika", "PDF/PNG plakati za stol"] },
    { name: "Scale", tagline: "Za više lokala pod jednom markom", price: "Po dogovoru", period: "", cta: "Razgovarajmo", features: ["Sve iz Grow", "Više lokala, jedna ploča", "Zajednička analitika lanca", "Provjera računa preko blagajne", "Prioritetna podrška + API"] },
  ] },
  faq: { eyebrow: "Česta pitanja", h2: "Još nešto nejasno?", items: [
    { q: "Mora li gost preuzeti aplikaciju?", a: "Ne. Stranica se otvori u pregledniku putem QR koda na stolu. Registracija je jedan korak — Google ili broj telefona, bez lozinke." },
    { q: "Kako dobivam više Google recenzija?", a: "Automatski. Kad gost dobije pečat (dakle zadovoljan), pozovemo ga na recenziju na Googleu. Loša iskustva presretnemo privatno — tvoj profil dobije samo dobre recenzije." },
    { q: "Mogu li poslati poruku gostima kojih dugo nije bilo?", a: "Da. Vidiš segmente (aktivni, neaktivni 21+ dana, rođendani, najbolji) i jednim klikom pošalješ SMS ili email — ili pustiš da ide automatski." },
    { q: "Koliko košta slanje poruka?", a: "Email je praktički besplatan; SMS otprilike nekoliko centi po komadu — prije slanja pokažemo točan trošak, bez iznenađenja." },
    { q: "Radi li s mojom blagajnom?", a: "Da. Svaki fiskalni račun nosi QR kod — sustav čita izdavatelja i vrijeme izdavanja izravno iz njega. Svaki račun broji se samo jednom." },
    { q: "Koliko traje postavljanje?", a: "Oko pet minuta: upišeš ime, logo i boju, fotografiraš uzorak računa za aktivaciju, isprintaš QR. Gosti mogu skupljati pečate isti dan." },
  ] },
  finalCta: { h2: "Tvoja stalna kava počinje danas", p: "Izradi stranicu, isprintaj QR, stavi ga na stolove. Prve pečate možeš darovati već popodne.", cta1: "Izradi svoju stranicu", cta2: "Prvo pogledaj demo" },
  footer: { tagline: "Vjernost, Google recenzije i marketing za lokale — gost skenira QR s računa, a ti gradiš bazu stalnih gostiju.", product: "Proizvod", company: "Tvrtka", legal: "Pravno", lProdukt: ["Značajke", "Cijene", "Kako radi", "Demo za goste", "Demo ploča"], lPodjetje: ["Kontakt", "Česta pitanja", "Prijava za lokale"], lPravno: ["Opći uvjeti", "Politika privatnosti", "Kolačići"], rights: "Sva prava pridržana." },
  kontakt: { eyebrow: "Sve ti postavimo", h1: "Donesemo ti više stalnih gostiju", p: "Ostavi podatke i u jednom danu ti sve postavimo — stranicu, kolo sreće, QR plakat. 14 dana besplatno, bez kartice. Bez rizika za tebe.", bullets: ["Sve postavimo umjesto tebe", "Pokažemo demo u tvom lokalu", "Bez obveze — otkažeš bilo kada"], or: "Ili nam piši na", formTitle: "Ostavi upit", fName: "Ime i prezime", fVenue: "Ime lokala", fEmail: "Email", fPhone: "Telefon", fType: "Tip lokala", fCity: "Grad", fGuests: "Broj gostiju", fHeard: "Gdje si čuo za nas?", fMsg: "Poruka (neobavezno)", fMsgPh: "Što te najviše zanima?", choose: "Odaberi …", send: "Pošalji upit", sending: "Šaljem …", consent: "Slanjem prihvaćaš politiku privatnosti.", doneH: "Hvala! Javit ćemo ti se.", doneP: "Tvoj upit smo primili. Uskoro te kontaktiramo i dogovorimo demo.", doneCta: "Natrag na početnu", errBoth: "Upiši barem email ili telefon da te možemo kontaktirati.", types: ["Kafić", "Bistro / restoran", "Pizzeria", "Pekarnica", "Slastičarnica", "Bar", "Frizer / salon", "Ostalo"], guests: ["Do 50 / dan", "50–150 / dan", "150–300 / dan", "Više od 300 / dan"], heard: ["Google", "Preporuka poznanika", "Instagram / Facebook", "Drugdje"] },
};

const en: Dict = {
  promo: "🎉 Launch offer — 14 days free, no card · set up in 5 minutes →",
  nav: { kako: "How it works", funkcije: "Features", cene: "Pricing", kontakt: "Contact", demo: "See demo", cta: "Create page" },
  hero: { badge: "Loyalty · Google reviews · marketing — for venues", h1a: "Regulars don't just happen. ", h1b: "You build them.", sub: "Guests scan the QR on their receipt and collect stamps — no app. You build a database of your regulars and their contacts you can reach anytime — new offers, win-backs, birthdays — and that earns you Google reviews.", cta1: "Create your page", cta2: "See live demo", c1: "Set up in 5 minutes", c2: "No fee per visit" },
  trust: { label: "Built for:", words: ["Cafés", "Bistros", "Bakeries", "Pizzerias", "Pâtisseries"] },
  kako: { eyebrow: "It's this simple", h2: "From receipt to stamp in three seconds", p: "Every fiscal receipt carries a QR code. The guest scans it, the system verifies the issuer and date — the stamp is there.", steps: [
    { title: "Scan the receipt", text: "The guest opens your page via the QR on the table and scans the QR on the receipt. No app download." },
    { title: "Get a stamp", text: "A stamp lands on the card — like on paper, only here it never gets lost." },
    { title: "Redeem the reward", text: "A full card = a free coffee. The guest shows a code, staff confirm with a tap. They come back sooner than you'd think." },
  ] },
  asset: { eyebrow: "Your real advantage", h2a: "Every guest becomes a contact in ", h2accent: "your", h2b: " database", p: "Every time someone scans, you gain a new regular — phone or email + visit pattern. The database grows by itself and is yours alone. You can reach it anytime:", bullets: ["Promote a new offer or dish", "Announce seasonal deals and events", "Share venue news", "Win back the inactive, delight on birthdays"], note: "No Facebook, no paid ads — you message directly the people who already come to you.", count: "regulars · +12 this month", grows: "↑ growing", sendAll: "Send everyone an offer" },
  dash: { eyebrow: "Your dashboard", h2: "See who comes back — and when", p: "How many scans, how many new guests, your busiest hours and who your best guests are. No Excel sheets.", feats: [["Live analytics", " — scans, visits by hour, return frequency."], ["QR table poster", " — download PNG or PDF and print in a minute."], ["Guest list", " — who's new, who's a regular, who you haven't seen in a while."]], cta: "Explore the dashboard", range: "Last 30 days", hours: "Visits by hour" },
  feat: { eyebrow: "More than stamps", h2: "A full machine for regulars", p: "Loyalty captures your regulars and their contacts. Everything else brings them back — and earns you Google reviews.", gBadge: "⭐ Google reviews on autopilot", gH3: "More happy guests = more reviews on Google", gP: "When a guest gets a stamp (so they're happy!), we automatically invite them to review. Bad experiences are caught privately — your profile gets only good reviews, and you rank higher in Google search.", gWas: "was 3.9★", gNew: "new reviews / 6 mo", gChart: "New Google reviews / month", items: [
    { label: "Lucky wheel", title: "Turn passers-by into regulars", text: "On your website or a QR poster, visitors spin the wheel, win a prize and register. Every spin = a new contact you can bring back." },
    { label: "Win-back", title: "Bring back those who vanished", text: "The system notices who hasn't been in for 3 weeks and sends a »we miss you« + bonus. A guest who'd otherwise go to a competitor returns — with zero effort from you." },
    { label: "Birthday", title: "Delight them right on their birthday", text: "We collect the date at sign-up. On their birthday we automatically send a gift — one of the strongest reasons to return." },
    { label: "SMS + email", title: "Reach every guest in one click", text: "Target segments — active, inactive, best, birthdays. Before sending we show the exact cost, so you never overpay." },
    { label: "Coupons", title: "Send rewards that actually bring them back", text: "Attach a real coupon (e.g. a free coffee) with an expiry and a reminder before it lapses — a concrete incentive, not just words." },
    { label: "Guest profiles", title: "Learn who your best guests are", text: "Click a guest and see everything: visits, spend, how often they return, when they were last in. You know who to reward and who to bring back." },
  ] },
  story: { eyebrow: "Our one memorable thing", h2a: "The feel of a real stamp,", h2b: "no paper in your pocket", p: "Loyalty cards worked because they were tangible. We kept exactly that moment — a stamp that lands when you scan — only you can't lose it or leave it at home.", left: "9 / 10 — one more visit ☕" },
  cene: { eyebrow: "Pricing", h2: "Pick your cup", p: "No fee per visit, no lock-in. 14 days free — no card.", trial: "✓ 14-day free trial on all plans", note: "All prices excl. VAT · cancel anytime · 14 days free, no card", popular: "Most popular", plans: [
    { name: "Start", tagline: "For one venue getting started", price: "€49.99", period: "/ month", cta: "Start 14 days free", features: ["1 venue", "Guest QR page + lucky wheel", "Stamps or points + rewards", "Up to 50 guests", "Basic analytics"] },
    { name: "Grow", tagline: "A full machine for regulars", price: "€79.99", period: "/ month", cta: "Start 14 days free", features: ["Everything in Start", "Unlimited guests", "⭐ Google reviews on autopilot", "Win-back & birthday automations", "SMS + email campaigns (segments)", "Guest profiles + full analytics", "PDF/PNG table posters"] },
    { name: "Scale", tagline: "For multiple venues under one brand", price: "Custom", period: "", cta: "Let's talk", features: ["Everything in Grow", "Multiple venues, one dashboard", "Chain-wide analytics", "Receipt verification via POS", "Priority support + API"] },
  ] },
  faq: { eyebrow: "FAQ", h2: "Anything still unclear?", items: [
    { q: "Does the guest need to install an app?", a: "No. The page opens in the browser via the QR code on the table. Sign-up is one step — Google or a phone number, no password." },
    { q: "How do I get more Google reviews?", a: "Automatically. When a guest gets a stamp (so they're happy), we invite them to review on Google. Bad experiences are caught privately so you can fix them before they go public — your profile gets only good reviews." },
    { q: "Can I message guests who haven't been in a while?", a: "Yes. You see segments (active, inactive 21+ days, birthdays, best) and message them via SMS or email in one click — or let it run automatically." },
    { q: "How much does messaging cost?", a: "Email is practically free; SMS is a few cents each — before sending we show the exact cost, no surprises." },
    { q: "Does it work with my register?", a: "Yes. Every Slovenian fiscal receipt carries a QR code — the system reads the issuer and issue time straight from it. Each receipt counts only once." },
    { q: "How long does setup take?", a: "About five minutes: enter your name, logo and color, photograph a sample receipt to activate, print the QR. Guests can start collecting stamps the same day." },
  ] },
  finalCta: { h2: "Your loyal coffee starts today", p: "Create the page, print the QR, put it on the tables. You can hand out the first stamps this afternoon.", cta1: "Create your page", cta2: "See the demo first" },
  footer: { tagline: "Loyalty, Google reviews and marketing for venues — guests scan the QR on their receipt, and you build a database of regulars.", product: "Product", company: "Company", legal: "Legal", lProdukt: ["Features", "Pricing", "How it works", "Guest demo", "Demo dashboard"], lPodjetje: ["Contact", "FAQ", "Venue login"], lPravno: ["Terms of service", "Privacy policy", "Cookies"], rights: "All rights reserved." },
  kontakt: { eyebrow: "We set it all up", h1: "Let's get you more regulars", p: "Leave your details and we'll set everything up in a day — page, lucky wheel, QR poster. 14 days free, no card. No risk for you.", bullets: ["We set everything up for you", "We show a demo at your venue", "No lock-in — cancel anytime"], or: "Or email us at", formTitle: "Leave an enquiry", fName: "Full name", fVenue: "Venue name", fEmail: "Email", fPhone: "Phone", fType: "Venue type", fCity: "City", fGuests: "Guests / day", fHeard: "How did you hear about us?", fMsg: "Message (optional)", fMsgPh: "What are you most interested in?", choose: "Choose …", send: "Send enquiry", sending: "Sending …", consent: "By sending you agree to the privacy policy.", doneH: "Thanks! We'll be in touch.", doneP: "We've received your enquiry. We'll contact you shortly to arrange a demo.", doneCta: "Back home", errBoth: "Enter at least an email or phone so we can reach you.", types: ["Café", "Bistro / restaurant", "Pizzeria", "Bakery", "Pâtisserie", "Bar", "Hair / salon", "Other"], guests: ["Up to 50 / day", "50–150 / day", "150–300 / day", "More than 300 / day"], heard: ["Google", "Word of mouth", "Instagram / Facebook", "Elsewhere"] },
};

export const T: Record<Lang, Dict> = { sl, hr, en };
